import type { AdvisorMod, AdvisorSignals } from '../types'

/**
 * A snapshot of the real catalog (name, category, description, commands), as
 * catalog.json listed it before any mod carried `signals`: what the advisor
 * must judge sensibly from words alone.
 */
const ROWS: readonly (readonly [string, string, string, (readonly string[])?])[] = [
  ["mod-store", "core", "An in-terminal app store: browse, search, install and update every Claude Mod from GitHub."],
  ["secret-shield", "security", "Blocks edits and writes that would commit API keys, tokens or private keys."],
  ["env-guard", "security", "Protects .env files, SSH keys and credential stores from being read or modified."],
  ["rm-rf-guard", "security", "Blocks catastrophic shell commands like rm -rf /, mkfs, dd to disks and chmod -R 777."],
  ["force-push-guard", "security", "Forbids force-pushing to protected branches and suggests --force-with-lease."],
  ["prod-guard", "security", "Stops production-affecting commands (terraform apply, kubectl on prod, DROP TABLE) unless explicitly allowed."],
  ["redactor", "security", "Masks secrets and personal data in tool results before the model ever reads them."],
  ["path-jail", "security", "Allows writes only inside the project root, resolving symlinks and .. tricks."],
  ["curl-pipe-guard", "security", "Blocks piping downloaded scripts straight into a shell."],
  ["dependency-sentinel", "security", "Flags typosquatted or brand-new packages before npm, pip or cargo installs them."],
  ["lockfile-guard", "security", "Prevents hand-editing lockfiles; they must change through the package manager."],
  ["git-status-line", "git", "Shows the current branch, ahead/behind and dirty file count in the status line."],
  ["auto-checkpoint", "git", "Snapshots your work tree before every editing turn and lets you /rollback to any checkpoint."],
  ["commit-composer", "git", "/commit writes a Conventional Commit message from your staged diff and commits it.", ["/commit"]],
  ["branch-namer", "git", "/git-branch creates a well-named git branch from a short task description."],
  ["main-branch-warn", "git", "Warns you the moment Claude starts editing files directly on main or master."],
  ["diff-pane", "git", "A live pane listing changed files with +/- line counts, updated after every edit."],
  ["pr-describer", "git", "/pr-desc drafts a pull request title and description from your branch diff."],
  ["conflict-helper", "git", "Detects merge-conflict markers and walks you through resolving each one."],
  ["co-author-stamp", "git", "Adds configurable Co-authored-by trailers to commits Claude makes."],
  ["gitignore-guard", "git", "Warns before node_modules, build output, OS junk or huge files get staged."],
  ["cost-meter", "cost", "Live session cost estimate in the status line, from real token usage."],
  ["token-budget", "cost", "Set a token or dollar budget per session; get warned at 80% and stopped at 100%."],
  ["context-gauge", "cost", "A slim band above the prompt showing how full the context window is."],
  ["cache-hit-meter", "cost", "Shows what share of input tokens came from the prompt cache."],
  ["turn-timer", "cost", "Times every turn and tells you when one runs long."],
  ["big-read-guard", "cost", "Stops full reads of huge files and nudges toward offset/limit or grep."],
  ["output-trimmer", "cost", "Trims huge command outputs to head, tail and error lines before they flood the context."],
  ["daily-spend", "cost", "Tracks spend per day and week across sessions with a /spend report."],
  ["model-advisor", "cost", "Suggests a cheaper model when your prompt is simple, and a stronger one when it is hard."],
  ["compact-coach", "cost", "Suggests /compact at natural breakpoints, before the context gets tight."],
  ["quote-selection", "productivity", "/quote pastes your mouse selection into the prompt as a Markdown quote."],
  ["prompt-snippets", "productivity", "Type :review:, :tests: or your own shortcodes and they expand into full prompts."],
  ["todo-pane", "productivity", "A live pane of Claude's current task list with progress."],
  ["focus-timer", "productivity", "A Pomodoro timer in the status line with focus and break cycles."],
  ["scratchpad", "productivity", "A persistent per-project notes pane you can type into without leaving Claude Code."],
  ["recent-files", "productivity", "/recent lists the files read and edited in this session, newest first."],
  ["copy-last", "productivity", "/copy-last copies Claude's last answer (or its last code block) to the clipboard."],
  ["prompt-history", "productivity", "/history searches every prompt you have sent across sessions and reuses one."],
  ["quick-commands", "productivity", "Short aliases like /t, /l and /b that run your test, lint and build commands."],
  ["idle-nudge", "productivity", "Reminds you about uncommitted changes after a stretch of inactivity."],
  ["auto-format", "quality", "Formats every file Claude edits with the right formatter for its language."],
  ["lint-on-save", "quality", "Runs the linter on each edited file and hands the errors straight back to Claude."],
  ["test-watch", "quality", "Runs the tests related to what changed and shows pass/fail in the status line."],
  ["typecheck-gate", "quality", "Type-checks the project at the end of every editing turn so errors never slip by."],
  ["no-skip-tests", "quality", "Blocks Claude from silencing tests with .skip, .only, xit or skip markers."],
  ["todo-tracker", "quality", "Notices every TODO, FIXME and HACK Claude adds and lists them at turn end."],
  ["debug-catcher", "quality", "Warns when console.log, print, debugger or dbg! statements are left in code."],
  ["no-any", "quality", "Flags new any types, @ts-ignore and eslint-disable comments as Claude writes them."],
  ["file-size-watch", "quality", "Warns when an edited file grows past a size that hurts readability."],
  ["test-first", "quality", "A TDD mode: no production code changes until a test has been written or changed."],
  ["tool-timeline", "observability", "A timeline pane of every tool call with duration, status and input summary."],
  ["files-touched", "observability", "A pane of every file read, edited or created in the session, with counts."],
  ["session-stats", "observability", "/session-stats shows a dashboard of turns, tools, tokens, cost, duration and files.", ["/session-stats"]],
  ["subagent-monitor", "observability", "Watch running subagents live: type, status, duration and last activity."],
  ["error-feed", "observability", "Collects every failed command and tool error in one pane."],
  ["activity-heatmap", "observability", "A heat map of when you use Claude Code, by hour and weekday."],
  ["bash-history", "observability", "/bash-history lists recent shell commands Claude ran, with exit status and duration."],
  ["web-trail", "observability", "/sources lists every page Claude fetched or searched this session."],
  ["permission-log", "observability", "Keeps a log of every tool call that was denied, and why."],
  ["token-sparkline", "observability", "A sparkline of tokens per turn right above the prompt."],
  ["house-style", "prompting", "Injects your team's style guide (STYLE.md) into the system prompt automatically."],
  ["language-lock", "prompting", "Makes Claude always answer in your language while keeping code in English."],
  ["concise-mode", "prompting", "/concise toggles short, to-the-point answers."],
  ["prompt-enhancer", "prompting", "/enhance rewrites your draft prompt into a precise, well-scoped request."],
  ["ticket-linker", "prompting", "Turns ticket references like ABC-123 or #42 into links and context for Claude."],
  ["date-context", "prompting", "Gives Claude the current date, time zone, branch and OS on every prompt."],
  ["persona-switch", "prompting", "/persona switches Claude between reviewer, architect, teacher and other roles."],
  ["explain-level", "prompting", "/eli5, /normal and /expert set how deep Claude's explanations go."],
  ["stack-detector", "prompting", "Detects your stack and gives Claude the right conventions for it."],
  ["prompt-lint", "prompting", "Gently flags vague prompts like 'fix it' and suggests what to add."],
  ["done-chime", "notifications", "Plays a chime when a long turn finishes."],
  ["speak-summary", "notifications", "Reads a one-line summary of what Claude did out loud when a turn ends."],
  ["permission-ping", "notifications", "Pings you with a sound and toast when Claude is waiting on your approval."],
  ["error-buzz", "notifications", "A short buzz when a command or test run fails."],
  ["webhook-notify", "notifications", "Posts to Slack, Discord, Teams or ntfy when a long task finishes."],
  ["desktop-notify", "notifications", "Native desktop notifications when Claude finishes or needs you."],
  ["long-run-alert", "notifications", "Alerts you when a single command has been running too long."],
  ["ci-watch", "notifications", "/ci-watch follows your GitHub Actions run and tells you the moment it passes or fails."],
  ["break-reminder", "notifications", "Reminds you to stand up and stretch every 50 minutes of active work."],
  ["celebrate", "notifications", "Celebrates when failing tests go green again."],
  ["decision-log", "memory", "/decide records an Architecture Decision Record in docs/decisions."],
  ["session-journal", "memory", "Writes a dated journal entry of what was done when the session ends."],
  ["glossary", "memory", "Teaches Claude your project's vocabulary and injects definitions when you use the terms."],
  ["bookmark", "memory", "/bookmark saves the last answer; /bookmarks lists and reuses them."],
  ["resume-brief", "memory", "Shows what you were working on last time when a new session starts."],
  ["lessons-learned", "memory", "When Claude fixes a mistake, offers to save the lesson to CLAUDE.md."],
  ["codebase-map", "memory", "/map builds a compact map of your repository and gives it to Claude."],
  ["snippet-vault", "memory", "Save and reuse code snippets across projects with /save-snippet and /snippet."],
  ["link-vault", "memory", "Collects every URL from the conversation into one list."],
  ["recall", "memory", "Gives Claude a recall tool to search your saved notes, decisions and journal."],
  ["changelog-keeper", "team", "Keeps CHANGELOG.md's Unreleased section up to date as you commit."],
  ["readme-sync", "team", "Warns when public APIs, CLI flags or env vars change but the docs do not."],
  ["standup", "team", "/standup summarises what you did yesterday, from git history, ready to paste."],
  ["review-agent", "team", "Adds a dedicated code-reviewer subagent and a /review command."],
  ["license-header", "team", "Adds your license header to every new source file Claude creates."],
  ["issue-drafter", "team", "/issue turns the current conversation into a well-structured GitHub issue."],
  ["handoff", "team", "/handoff writes a handoff note so a teammate can pick up exactly where you left off."],
  ["i18n-guard", "team", "Flags hard-coded user-facing strings in UI components."],
  ["migration-guard", "team", "Prevents editing database migrations that already exist; write a new one instead."],
  ["codeowners-hint", "team", "Shows who owns a file (from CODEOWNERS) as Claude edits it."],
  ["react-doctor", "stacks", "Catches React hook mistakes as Claude writes them: missing effect deps, setState in render, conditional hooks."],
  ["next-guard", "stacks", "Flags missing or needless \"use client\" and server-only imports leaking into client components in Next.js."],
  ["venv-guard", "stacks", "Blocks pip install outside an active virtualenv so system Python stays clean."],
  ["node-version-check", "stacks", "Warns when your Node version doesn't match .nvmrc, .node-version or package.json engines."],
  ["django-migrate-watch", "stacks", "After Django model changes, checks for missing migrations and offers to create them."],
  ["go-mod-tidy", "stacks", "Runs go mod tidy when Claude changes Go imports, so go.mod and go.sum stay in sync."],
  ["strict-types", "stacks", "Adds declare(strict_types=1) to new PHP files and from __future__ import annotations to new Python files."],
  ["schema-sync", "stacks", "After Prisma or Drizzle schema edits, regenerates the client and warns when a migration is missing."],
  ["env-example-sync", "stacks", "Keeps .env.example in sync with the environment variables your code actually reads."],
  ["monorepo-scope", "stacks", "Detects which monorepo package you're in and scopes test, lint and build commands to it."],
  ["docker-lint", "devops", "Flags Dockerfile smells: :latest tags, running as root, apt without cleanup, ADD instead of COPY."],
  ["k8s-dry-run", "devops", "Turns kubectl apply into a server-side dry run with a diff you approve first."],
  ["terraform-plan-pane", "devops", "Shows terraform plan as a clear pane of resources to create, change and destroy."],
  ["ci-yaml-check", "devops", "Checks edited GitHub Actions workflows and warns about actions not pinned to a version."],
  ["port-check", "devops", "Before a dev server starts, tells you if the port is already taken and by which process."],
  ["dev-server-pane", "devops", "Starts your dev server in the background and shows its errors in a live pane."],
  ["cloud-cost-warn", "devops", "Warns before commands that create expensive cloud resources like GPU instances or large databases."],
  ["log-tail", "devops", "/tail follows a log file or container in a live pane, with an errors-only filter."],
  ["docker-prune-guard", "devops", "Blocks docker system prune -a --volumes and volume deletion that can wipe local databases."],
  ["deploy-checklist", "devops", "Shows a pre-deploy checklist (tests, branch, changelog) and asks you to confirm before deploying."],
  ["sql-safety", "data", "Flags UPDATE and DELETE without WHERE in .sql files and in queries inside your code."],
  ["query-explain", "data", "/explain-query runs EXPLAIN on your local database and explains the plan in plain words."],
  ["seed-guard", "data", "Blocks database seed, reset and drop commands unless DATABASE_URL points at your own machine."],
  ["schema-pane", "data", "A pane of your local database's tables and columns, ready to hand to Claude as context."],
  ["n-plus-one-hint", "data", "Spots database queries inside loops, the classic N+1 problem, as Claude writes them."],
  ["migration-namer", "data", "Gives new migrations consistent, descriptive, timestamped names."],
  ["query-result-cap", "data", "Adds a LIMIT to ad-hoc SELECTs Claude runs in psql, mysql or sqlite so results don't flood the context."],
  ["backup-before-migrate", "data", "Dumps your local database before every migration so a bad one is one command away from undo."],
  ["csv-peek", "data", "/peek shows a CSV or JSONL file's columns, sample rows and inferred types without reading the whole file."],
  ["fixture-factory", "data", "/fixtures generates realistic test data that matches your schema or types."],
  ["a11y-guard", "frontend", "Flags accessibility misses as Claude writes UI: images without alt, unlabeled buttons, clickable divs."],
  ["screenshot-check", "frontend", "After UI edits, takes a Playwright screenshot of the page and shows it to Claude."],
  ["bundle-size-watch", "frontend", "Compares bundle size after each build and warns when it grows."],
  ["css-token-guard", "frontend", "Flags hard-coded hex colors and pixel values where your design tokens should be used."],
  ["lighthouse-run", "frontend", "/lighthouse runs Lighthouse on a URL and shows performance, a11y, SEO and best-practice scores in a pane."],
  ["heavy-asset-warn", "frontend", "Warns when large images, videos or fonts are added to the project."],
  ["storybook-nudge", "frontend", "Reminds you to add a story when Claude creates a new component without one."],
  ["contrast-checker", "frontend", "Checks that the colors Claude changes in CSS meet WCAG AA contrast."],
  ["dark-mode-check", "frontend", "Flags colors added without a dark-mode variant in projects that support a dark theme."],
  ["component-catalog", "frontend", "/components lists your existing UI components so Claude reuses them instead of creating duplicates."],
  ["http-client", "api", "/http sends a request and shows the formatted response in a pane, like a tiny Postman in your terminal."],
  ["openapi-sync", "api", "Warns when your API routes change but openapi.yaml doesn't."],
  ["url-allowlist", "api", "Restricts WebFetch to the domains you allow."],
  ["offline-mode", "api", "/offline blocks every network call — fetches, curl, installs, git push — until you turn it back on."],
  ["mock-server", "api", "/mock starts a fake API server from your OpenAPI spec so you can build the frontend before the backend."],
  ["rate-limit-guard", "api", "Stops Claude from hammering external APIs with curl loops."],
  ["jwt-decode", "api", "/jwt decodes a JSON Web Token locally — header, claims, expiry — without sending it anywhere."],
  ["status-check", "api", "/service-status checks whether GitHub, npm, PyPI or the Anthropic API are having an outage before you blame your code."],
  ["graphql-context", "api", "Gives Claude a compact summary of your GraphQL schema when you work on queries and resolvers."],
  ["curl-to-code", "api", "/curl2code turns a curl command into fetch, axios, Python requests or Go code."],
  ["scope-lock", "agents", "/scope locks Claude to the files you name; edits outside the scope are blocked."],
  ["second-opinion", "agents", "/second-opinion has a different model critique Claude's last answer or plan."],
  ["parallel-explore", "agents", "/explore sends three subagents to investigate different parts of the codebase and merges their findings."],
  ["subagent-cap", "agents", "Caps how many subagents can run at the same time."],
  ["task-queue", "agents", "/queue lines up prompts that run one after another whenever Claude is free."],
  ["night-shift", "agents", "Runs your queued tasks at a scheduled time, like overnight, and leaves you a report."],
  ["loop-breaker", "agents", "Stops Claude when it repeats the same failing command three times and suggests a different approach."],
  ["self-check", "agents", "At the end of each editing turn, has the model double-check it actually did what you asked."],
  ["edit-limit", "agents", "Asks for confirmation when a single turn tries to modify more than N files."],
  ["agent-presets", "agents", "Ready-made subagents for focused jobs: debugger, test writer, doc writer and migrator."],
  ["explain-diff", "learning", "/explain-diff explains in plain words what changed in the last turn and why."],
  ["quiz-me", "learning", "/quiz asks you questions about the code Claude just wrote, to check you really understand it."],
  ["learning-mode", "learning", "Claude explains the why behind each change and leaves small TODOs for you to complete yourself."],
  ["onboarding-tour", "learning", "/tour walks a newcomer through the repository step by step."],
  ["command-coach", "learning", "Suggests Claude Code commands and mods that fit the way you work."],
  ["shortcut-tips", "learning", "One tip a day about Claude Code shortcuts and features you might not know."],
  ["why-log", "learning", "Records why each file was changed; /why shows the reasoning behind any file's edits."],
  ["cheatsheet", "learning", "/cheat shows a quick reference for git, docker, regex, tmux and more, offline."],
  ["pair-mode", "learning", "Claude proposes, you type: edits become diffs you apply yourself, for deliberate practice."],
  ["skill-tracker", "learning", "Tracks which languages and tools you've worked with each week."],
  ["license-checker", "compliance", "Warns when a dependency with a copyleft license (GPL, AGPL) lands in a permissively licensed project."],
  ["pii-in-logs", "compliance", "Flags log statements that print emails, passwords, tokens or other personal data."],
  ["data-map", "compliance", "/data-map lists where your code collects, stores and sends personal data — a head start for GDPR."],
  ["tracker-guard", "compliance", "Blocks adding analytics and tracking SDKs that haven't been approved."],
  ["no-upload", "compliance", "Blocks commands that upload files to external services like pastebins and file-sharing sites."],
  ["crypto-guard", "compliance", "Flags weak cryptography: MD5 or SHA1 for passwords, Math.random for tokens, ECB mode, hard-coded IVs."],
  ["sbom", "compliance", "/sbom generates a software bill of materials with every dependency and its license."],
  ["audit-trail", "compliance", "Writes every action Claude takes to an append-only JSONL audit log."],
  ["vuln-scan", "compliance", "After installs, runs npm audit or pip-audit and shows any vulnerabilities in a pane."],
  ["copyright-guard", "compliance", "Flags pasted code that carries someone else's license or copyright header."],
  ["benchmark-compare", "performance", "/bench runs your benchmarks before and after a change and compares the numbers."],
  ["slow-test-flag", "performance", "Points out your slowest tests after each test run."],
  ["flaky-detector", "performance", "Detects tests that pass and fail at random and keeps a list of the suspects."],
  ["leak-hint", "performance", "Flags event listeners, intervals and subscriptions created without cleanup."],
  ["outdated-deps", "performance", "/outdated shows stale dependencies and how risky each upgrade is."],
  ["profile-run", "performance", "/profile runs a command under a profiler and shows the hottest functions."],
  ["net-retry", "performance", "Automatically retries commands that failed because of a temporary network error."],
  ["disk-guard", "performance", "Warns when the disk is nearly full before builds, installs and docker pulls."],
  ["regression-guard", "performance", "Remembers which tests passed at the start of the session and warns if any of them now fail."],
  ["watch-mode-guard", "performance", "Blocks watch-mode and never-ending commands run in the foreground, where they'd hang the turn."],
  ["mod-maker", "ecosystem", "/new-mod scaffolds a new Claude Code mod with manifest, hooks, test and README, ready to fill in."],
  ["mod-doctor", "ecosystem", "/mod-doctor checks your installed mods for outdated versions, conflicts and load errors."],
  ["mod-profiles", "ecosystem", "Switch between sets of mods — work, personal, demo — with one command."],
  ["settings-sync", "ecosystem", "Exports and imports your mods' configuration so you can move it between machines."],
  ["quiet-mode", "ecosystem", "/quiet silences toasts and sounds from every mod while you focus."],
  ["achievements", "ecosystem", "Unlock achievements as you work: first commit, 100 green test runs, a week-long streak and more."],
  ["streaks", "ecosystem", "Shows your consecutive days of coding with Claude in the status line."],
  ["soundpack", "ecosystem", "Sound packs for Claude Code events: minimal, retro or nature."],
  ["daily-goal", "ecosystem", "/daily-goal sets today's goal, keeps it in view above the prompt and asks at day's end if you got there."],
  ["session-replay", "ecosystem", "/replay steps through the session — prompts, tool calls, edits — in a pane, like a video timeline."],
  ["smart-router", "agents", "Routes every subagent to the right model for the task's difficulty, runs independent work in parallel and starts workflows when a job needs one."],
]

export const CATALOG_MODS: readonly AdvisorMod[] = ROWS.map(([name, category, description, commands]) => ({
  name,
  category,
  description,
  ...(commands === undefined ? {} : { commands: [...commands] }),
}))

/** Real `signals` of a few mods, as catalog.json carries them since they were added. */
export const REAL_SIGNALS: Readonly<Record<string, AdvisorSignals>> = {
  'docker-lint': {"files": ["Dockerfile", "Dockerfile.*", "**/Dockerfile", "**/Dockerfile.*", "*.dockerfile", "Containerfile"], "intents": ["dockerfile", "docker", "docker image", "container image", "dockerize", "lint dockerfile", "hadolint", "docker build", "multi-stage build", "immagine docker"]},
  'next-guard': {"files": ["next.config.js", "next.config.mjs", "next.config.ts", "app/**/page.tsx", "src/app/**/page.tsx"], "deps": ["next"], "intents": ["use client", "server component", "server components", "client component", "next.js", "nextjs", "app router", "next/headers", "server-only", "hydration error"]},
  'schema-sync': {"files": ["prisma/schema.prisma", "**/*.prisma", "drizzle.config.ts", "drizzle.config.js", "drizzle.config.mjs"], "deps": ["prisma", "@prisma/client", "drizzle-orm", "drizzle-kit"], "intents": ["prisma", "drizzle", "schema change", "prisma generate", "orm schema", "migration missing", "update prisma schema", "modifica allo schema", "genera il client prisma"]},
  'commit-composer': {"files": ["commitlint.config.*", ".commitlintrc*"], "deps": ["@commitlint/cli", "@commitlint/config-conventional", "commitlint"], "intents": ["commit message", "conventional commit", "conventional commits", "write a commit", "commit changes", "staged diff", "messaggio di commit", "fai il commit"]},
  'deploy-checklist': {"files": ["vercel.json", "netlify.toml", "fly.toml", "firebase.json", "app.yaml", "wrangler.toml", "wrangler.jsonc", "railway.json", "render.yaml", "Procfile"], "deps": ["vercel", "netlify-cli", "firebase-tools", "wrangler"], "intents": ["deploy", "deployment", "release", "go live", "publish to npm", "npm publish", "pre-deploy", "rilascio", "rilasciare", "pubblicare"]},
  'k8s-dry-run': {"files": ["k8s/**", "kubernetes/**", "manifests/**", "**/Chart.yaml", "**/kustomization.yaml", "skaffold.yaml", "helmfile.yaml"], "intents": ["kubectl", "kubernetes", "k8s", "kubectl apply", "dry run", "manifests", "helm", "apply manifests", "manifest kubernetes"]},
  'go-mod-tidy': {"files": ["go.mod", "go.work"], "intents": ["go mod tidy", "go modules", "go.mod", "go dependencies", "go imports", "go.sum out of sync", "dipendenze go", "moduli go"]},
  'dependency-sentinel': {"files": ["package.json", "requirements.txt", "pyproject.toml", "Cargo.toml", "go.mod", "Gemfile", "composer.json"], "intents": ["typosquatting", "malicious package", "supply chain", "hallucinated package", "suspicious dependency", "new dependency", "add a package", "npm install", "package typo", "pacchetto sospetto"]},
  'cost-meter': {"intents": ["session cost", "how much spent", "spend", "token cost", "api cost", "cost estimate", "price of this session", "costo", "quanto ho speso"], "always": true},
  'git-status-line': {"intents": ["git status", "current branch", "which branch am i on", "ahead behind", "dirty files", "uncommitted changes", "status line", "stato git", "ramo corrente"], "always": true},
  'slow-test-flag': {"deps": ["jest", "vitest", "mocha", "pytest"], "intents": ["slow tests", "slowest tests", "test duration", "tests take too long", "speed up tests", "test performance", "durations", "test lenti", "test troppo lenti"]},
}
